
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Candidate` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Candidate
 * 
 */
export type CandidateModel = runtime.Types.Result.DefaultSelection<Prisma.$CandidatePayload>

export type AggregateCandidate = {
  _count: CandidateCountAggregateOutputType | null
  _min: CandidateMinAggregateOutputType | null
  _max: CandidateMaxAggregateOutputType | null
}

export type CandidateMinAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  positionId: string | null
  status: string | null
  resumeUrl: string | null
  createdBy: string | null
  createdAt: Date | null
}

export type CandidateMaxAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  positionId: string | null
  status: string | null
  resumeUrl: string | null
  createdBy: string | null
  createdAt: Date | null
}

export type CandidateCountAggregateOutputType = {
  id: number
  name: number
  email: number
  positionId: number
  status: number
  resumeUrl: number
  createdBy: number
  createdAt: number
  _all: number
}


export type CandidateMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  positionId?: true
  status?: true
  resumeUrl?: true
  createdBy?: true
  createdAt?: true
}

export type CandidateMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  positionId?: true
  status?: true
  resumeUrl?: true
  createdBy?: true
  createdAt?: true
}

export type CandidateCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  positionId?: true
  status?: true
  resumeUrl?: true
  createdBy?: true
  createdAt?: true
  _all?: true
}

export type CandidateAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Candidate to aggregate.
   */
  where?: Prisma.CandidateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Candidates to fetch.
   */
  orderBy?: Prisma.CandidateOrderByWithRelationInput | Prisma.CandidateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CandidateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Candidates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Candidates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Candidates
  **/
  _count?: true | CandidateCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CandidateMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CandidateMaxAggregateInputType
}

export type GetCandidateAggregateType<T extends CandidateAggregateArgs> = {
      [P in keyof T & keyof AggregateCandidate]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCandidate[P]>
    : Prisma.GetScalarType<T[P], AggregateCandidate[P]>
}




export type CandidateGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CandidateWhereInput
  orderBy?: Prisma.CandidateOrderByWithAggregationInput | Prisma.CandidateOrderByWithAggregationInput[]
  by: Prisma.CandidateScalarFieldEnum[] | Prisma.CandidateScalarFieldEnum
  having?: Prisma.CandidateScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CandidateCountAggregateInputType | true
  _min?: CandidateMinAggregateInputType
  _max?: CandidateMaxAggregateInputType
}

export type CandidateGroupByOutputType = {
  id: string
  name: string
  email: string
  positionId: string
  status: string
  resumeUrl: string | null
  createdBy: string
  createdAt: Date
  _count: CandidateCountAggregateOutputType | null
  _min: CandidateMinAggregateOutputType | null
  _max: CandidateMaxAggregateOutputType | null
}

type GetCandidateGroupByPayload<T extends CandidateGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CandidateGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CandidateGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CandidateGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CandidateGroupByOutputType[P]>
      }
    >
  >



export type CandidateWhereInput = {
  AND?: Prisma.CandidateWhereInput | Prisma.CandidateWhereInput[]
  OR?: Prisma.CandidateWhereInput[]
  NOT?: Prisma.CandidateWhereInput | Prisma.CandidateWhereInput[]
  id?: Prisma.StringFilter<"Candidate"> | string
  name?: Prisma.StringFilter<"Candidate"> | string
  email?: Prisma.StringFilter<"Candidate"> | string
  positionId?: Prisma.StringFilter<"Candidate"> | string
  status?: Prisma.StringFilter<"Candidate"> | string
  resumeUrl?: Prisma.StringNullableFilter<"Candidate"> | string | null
  createdBy?: Prisma.StringFilter<"Candidate"> | string
  createdAt?: Prisma.DateTimeFilter<"Candidate"> | Date | string
  position?: Prisma.XOR<Prisma.PositionScalarRelationFilter, Prisma.PositionWhereInput>
  creator?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  interviews?: Prisma.InterviewListRelationFilter
}

export type CandidateOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  positionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  resumeUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  position?: Prisma.PositionOrderByWithRelationInput
  creator?: Prisma.UserOrderByWithRelationInput
  interviews?: Prisma.InterviewOrderByRelationAggregateInput
}

export type CandidateWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CandidateWhereInput | Prisma.CandidateWhereInput[]
  OR?: Prisma.CandidateWhereInput[]
  NOT?: Prisma.CandidateWhereInput | Prisma.CandidateWhereInput[]
  name?: Prisma.StringFilter<"Candidate"> | string
  email?: Prisma.StringFilter<"Candidate"> | string
  positionId?: Prisma.StringFilter<"Candidate"> | string
  status?: Prisma.StringFilter<"Candidate"> | string
  resumeUrl?: Prisma.StringNullableFilter<"Candidate"> | string | null
  createdBy?: Prisma.StringFilter<"Candidate"> | string
  createdAt?: Prisma.DateTimeFilter<"Candidate"> | Date | string
  position?: Prisma.XOR<Prisma.PositionScalarRelationFilter, Prisma.PositionWhereInput>
  creator?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  interviews?: Prisma.InterviewListRelationFilter
}, "id">

export type CandidateOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  positionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  resumeUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CandidateCountOrderByAggregateInput
  _max?: Prisma.CandidateMaxOrderByAggregateInput
  _min?: Prisma.CandidateMinOrderByAggregateInput
}

export type CandidateScalarWhereWithAggregatesInput = {
  AND?: Prisma.CandidateScalarWhereWithAggregatesInput | Prisma.CandidateScalarWhereWithAggregatesInput[]
  OR?: Prisma.CandidateScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CandidateScalarWhereWithAggregatesInput | Prisma.CandidateScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Candidate"> | string
  name?: Prisma.StringWithAggregatesFilter<"Candidate"> | string
  email?: Prisma.StringWithAggregatesFilter<"Candidate"> | string
  positionId?: Prisma.StringWithAggregatesFilter<"Candidate"> | string
  status?: Prisma.StringWithAggregatesFilter<"Candidate"> | string
  resumeUrl?: Prisma.StringNullableWithAggregatesFilter<"Candidate"> | string | null
  createdBy?: Prisma.StringWithAggregatesFilter<"Candidate"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Candidate"> | Date | string
}

export type CandidateCreateInput = {
  id?: string
  name: string
  email: string
  status?: string
  resumeUrl?: string | null
  createdAt?: Date | string
  position: Prisma.PositionCreateNestedOneWithoutCandidatesInput
  creator: Prisma.UserCreateNestedOneWithoutCandidatesInput
  interviews?: Prisma.InterviewCreateNestedManyWithoutCandidateInput
}

export type CandidateUncheckedCreateInput = {
  id?: string
  name: string
  email: string
  positionId: string
  status?: string
  resumeUrl?: string | null
  createdBy: string
  createdAt?: Date | string
  interviews?: Prisma.InterviewUncheckedCreateNestedManyWithoutCandidateInput
}

export type CandidateUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  position?: Prisma.PositionUpdateOneRequiredWithoutCandidatesNestedInput
  creator?: Prisma.UserUpdateOneRequiredWithoutCandidatesNestedInput
  interviews?: Prisma.InterviewUpdateManyWithoutCandidateNestedInput
}

export type CandidateUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  positionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  interviews?: Prisma.InterviewUncheckedUpdateManyWithoutCandidateNestedInput
}

export type CandidateCreateManyInput = {
  id?: string
  name: string
  email: string
  positionId: string
  status?: string
  resumeUrl?: string | null
  createdBy: string
  createdAt?: Date | string
}

export type CandidateUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CandidateUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  positionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CandidateListRelationFilter = {
  every?: Prisma.CandidateWhereInput
  some?: Prisma.CandidateWhereInput
  none?: Prisma.CandidateWhereInput
}

export type CandidateOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CandidateCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  positionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  resumeUrl?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CandidateMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  positionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  resumeUrl?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CandidateMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  positionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  resumeUrl?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CandidateScalarRelationFilter = {
  is?: Prisma.CandidateWhereInput
  isNot?: Prisma.CandidateWhereInput
}

export type CandidateCreateNestedManyWithoutCreatorInput = {
  create?: Prisma.XOR<Prisma.CandidateCreateWithoutCreatorInput, Prisma.CandidateUncheckedCreateWithoutCreatorInput> | Prisma.CandidateCreateWithoutCreatorInput[] | Prisma.CandidateUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.CandidateCreateOrConnectWithoutCreatorInput | Prisma.CandidateCreateOrConnectWithoutCreatorInput[]
  createMany?: Prisma.CandidateCreateManyCreatorInputEnvelope
  connect?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
}

export type CandidateUncheckedCreateNestedManyWithoutCreatorInput = {
  create?: Prisma.XOR<Prisma.CandidateCreateWithoutCreatorInput, Prisma.CandidateUncheckedCreateWithoutCreatorInput> | Prisma.CandidateCreateWithoutCreatorInput[] | Prisma.CandidateUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.CandidateCreateOrConnectWithoutCreatorInput | Prisma.CandidateCreateOrConnectWithoutCreatorInput[]
  createMany?: Prisma.CandidateCreateManyCreatorInputEnvelope
  connect?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
}

export type CandidateUpdateManyWithoutCreatorNestedInput = {
  create?: Prisma.XOR<Prisma.CandidateCreateWithoutCreatorInput, Prisma.CandidateUncheckedCreateWithoutCreatorInput> | Prisma.CandidateCreateWithoutCreatorInput[] | Prisma.CandidateUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.CandidateCreateOrConnectWithoutCreatorInput | Prisma.CandidateCreateOrConnectWithoutCreatorInput[]
  upsert?: Prisma.CandidateUpsertWithWhereUniqueWithoutCreatorInput | Prisma.CandidateUpsertWithWhereUniqueWithoutCreatorInput[]
  createMany?: Prisma.CandidateCreateManyCreatorInputEnvelope
  set?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  disconnect?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  delete?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  connect?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  update?: Prisma.CandidateUpdateWithWhereUniqueWithoutCreatorInput | Prisma.CandidateUpdateWithWhereUniqueWithoutCreatorInput[]
  updateMany?: Prisma.CandidateUpdateManyWithWhereWithoutCreatorInput | Prisma.CandidateUpdateManyWithWhereWithoutCreatorInput[]
  deleteMany?: Prisma.CandidateScalarWhereInput | Prisma.CandidateScalarWhereInput[]
}

export type CandidateUncheckedUpdateManyWithoutCreatorNestedInput = {
  create?: Prisma.XOR<Prisma.CandidateCreateWithoutCreatorInput, Prisma.CandidateUncheckedCreateWithoutCreatorInput> | Prisma.CandidateCreateWithoutCreatorInput[] | Prisma.CandidateUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.CandidateCreateOrConnectWithoutCreatorInput | Prisma.CandidateCreateOrConnectWithoutCreatorInput[]
  upsert?: Prisma.CandidateUpsertWithWhereUniqueWithoutCreatorInput | Prisma.CandidateUpsertWithWhereUniqueWithoutCreatorInput[]
  createMany?: Prisma.CandidateCreateManyCreatorInputEnvelope
  set?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  disconnect?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  delete?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  connect?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  update?: Prisma.CandidateUpdateWithWhereUniqueWithoutCreatorInput | Prisma.CandidateUpdateWithWhereUniqueWithoutCreatorInput[]
  updateMany?: Prisma.CandidateUpdateManyWithWhereWithoutCreatorInput | Prisma.CandidateUpdateManyWithWhereWithoutCreatorInput[]
  deleteMany?: Prisma.CandidateScalarWhereInput | Prisma.CandidateScalarWhereInput[]
}

export type CandidateCreateNestedManyWithoutPositionInput = {
  create?: Prisma.XOR<Prisma.CandidateCreateWithoutPositionInput, Prisma.CandidateUncheckedCreateWithoutPositionInput> | Prisma.CandidateCreateWithoutPositionInput[] | Prisma.CandidateUncheckedCreateWithoutPositionInput[]
  connectOrCreate?: Prisma.CandidateCreateOrConnectWithoutPositionInput | Prisma.CandidateCreateOrConnectWithoutPositionInput[]
  createMany?: Prisma.CandidateCreateManyPositionInputEnvelope
  connect?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
}

export type CandidateUncheckedCreateNestedManyWithoutPositionInput = {
  create?: Prisma.XOR<Prisma.CandidateCreateWithoutPositionInput, Prisma.CandidateUncheckedCreateWithoutPositionInput> | Prisma.CandidateCreateWithoutPositionInput[] | Prisma.CandidateUncheckedCreateWithoutPositionInput[]
  connectOrCreate?: Prisma.CandidateCreateOrConnectWithoutPositionInput | Prisma.CandidateCreateOrConnectWithoutPositionInput[]
  createMany?: Prisma.CandidateCreateManyPositionInputEnvelope
  connect?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
}

export type CandidateUpdateManyWithoutPositionNestedInput = {
  create?: Prisma.XOR<Prisma.CandidateCreateWithoutPositionInput, Prisma.CandidateUncheckedCreateWithoutPositionInput> | Prisma.CandidateCreateWithoutPositionInput[] | Prisma.CandidateUncheckedCreateWithoutPositionInput[]
  connectOrCreate?: Prisma.CandidateCreateOrConnectWithoutPositionInput | Prisma.CandidateCreateOrConnectWithoutPositionInput[]
  upsert?: Prisma.CandidateUpsertWithWhereUniqueWithoutPositionInput | Prisma.CandidateUpsertWithWhereUniqueWithoutPositionInput[]
  createMany?: Prisma.CandidateCreateManyPositionInputEnvelope
  set?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  disconnect?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  delete?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  connect?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  update?: Prisma.CandidateUpdateWithWhereUniqueWithoutPositionInput | Prisma.CandidateUpdateWithWhereUniqueWithoutPositionInput[]
  updateMany?: Prisma.CandidateUpdateManyWithWhereWithoutPositionInput | Prisma.CandidateUpdateManyWithWhereWithoutPositionInput[]
  deleteMany?: Prisma.CandidateScalarWhereInput | Prisma.CandidateScalarWhereInput[]
}

export type CandidateUncheckedUpdateManyWithoutPositionNestedInput = {
  create?: Prisma.XOR<Prisma.CandidateCreateWithoutPositionInput, Prisma.CandidateUncheckedCreateWithoutPositionInput> | Prisma.CandidateCreateWithoutPositionInput[] | Prisma.CandidateUncheckedCreateWithoutPositionInput[]
  connectOrCreate?: Prisma.CandidateCreateOrConnectWithoutPositionInput | Prisma.CandidateCreateOrConnectWithoutPositionInput[]
  upsert?: Prisma.CandidateUpsertWithWhereUniqueWithoutPositionInput | Prisma.CandidateUpsertWithWhereUniqueWithoutPositionInput[]
  createMany?: Prisma.CandidateCreateManyPositionInputEnvelope
  set?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  disconnect?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  delete?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  connect?: Prisma.CandidateWhereUniqueInput | Prisma.CandidateWhereUniqueInput[]
  update?: Prisma.CandidateUpdateWithWhereUniqueWithoutPositionInput | Prisma.CandidateUpdateWithWhereUniqueWithoutPositionInput[]
  updateMany?: Prisma.CandidateUpdateManyWithWhereWithoutPositionInput | Prisma.CandidateUpdateManyWithWhereWithoutPositionInput[]
  deleteMany?: Prisma.CandidateScalarWhereInput | Prisma.CandidateScalarWhereInput[]
}

export type CandidateCreateNestedOneWithoutInterviewsInput = {
  create?: Prisma.XOR<Prisma.CandidateCreateWithoutInterviewsInput, Prisma.CandidateUncheckedCreateWithoutInterviewsInput>
  connectOrCreate?: Prisma.CandidateCreateOrConnectWithoutInterviewsInput
  connect?: Prisma.CandidateWhereUniqueInput
}

export type CandidateUpdateOneRequiredWithoutInterviewsNestedInput = {
  create?: Prisma.XOR<Prisma.CandidateCreateWithoutInterviewsInput, Prisma.CandidateUncheckedCreateWithoutInterviewsInput>
  connectOrCreate?: Prisma.CandidateCreateOrConnectWithoutInterviewsInput
  upsert?: Prisma.CandidateUpsertWithoutInterviewsInput
  connect?: Prisma.CandidateWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CandidateUpdateToOneWithWhereWithoutInterviewsInput, Prisma.CandidateUpdateWithoutInterviewsInput>, Prisma.CandidateUncheckedUpdateWithoutInterviewsInput>
}

export type CandidateCreateWithoutCreatorInput = {
  id?: string
  name: string
  email: string
  status?: string
  resumeUrl?: string | null
  createdAt?: Date | string
  position: Prisma.PositionCreateNestedOneWithoutCandidatesInput
  interviews?: Prisma.InterviewCreateNestedManyWithoutCandidateInput
}

export type CandidateUncheckedCreateWithoutCreatorInput = {
  id?: string
  name: string
  email: string
  positionId: string
  status?: string
  resumeUrl?: string | null
  createdAt?: Date | string
  interviews?: Prisma.InterviewUncheckedCreateNestedManyWithoutCandidateInput
}

export type CandidateCreateOrConnectWithoutCreatorInput = {
  where: Prisma.CandidateWhereUniqueInput
  create: Prisma.XOR<Prisma.CandidateCreateWithoutCreatorInput, Prisma.CandidateUncheckedCreateWithoutCreatorInput>
}

export type CandidateCreateManyCreatorInputEnvelope = {
  data: Prisma.CandidateCreateManyCreatorInput | Prisma.CandidateCreateManyCreatorInput[]
  skipDuplicates?: boolean
}

export type CandidateUpsertWithWhereUniqueWithoutCreatorInput = {
  where: Prisma.CandidateWhereUniqueInput
  update: Prisma.XOR<Prisma.CandidateUpdateWithoutCreatorInput, Prisma.CandidateUncheckedUpdateWithoutCreatorInput>
  create: Prisma.XOR<Prisma.CandidateCreateWithoutCreatorInput, Prisma.CandidateUncheckedCreateWithoutCreatorInput>
}

export type CandidateUpdateWithWhereUniqueWithoutCreatorInput = {
  where: Prisma.CandidateWhereUniqueInput
  data: Prisma.XOR<Prisma.CandidateUpdateWithoutCreatorInput, Prisma.CandidateUncheckedUpdateWithoutCreatorInput>
}

export type CandidateUpdateManyWithWhereWithoutCreatorInput = {
  where: Prisma.CandidateScalarWhereInput
  data: Prisma.XOR<Prisma.CandidateUpdateManyMutationInput, Prisma.CandidateUncheckedUpdateManyWithoutCreatorInput>
}

export type CandidateScalarWhereInput = {
  AND?: Prisma.CandidateScalarWhereInput | Prisma.CandidateScalarWhereInput[]
  OR?: Prisma.CandidateScalarWhereInput[]
  NOT?: Prisma.CandidateScalarWhereInput | Prisma.CandidateScalarWhereInput[]
  id?: Prisma.StringFilter<"Candidate"> | string
  name?: Prisma.StringFilter<"Candidate"> | string
  email?: Prisma.StringFilter<"Candidate"> | string
  positionId?: Prisma.StringFilter<"Candidate"> | string
  status?: Prisma.StringFilter<"Candidate"> | string
  resumeUrl?: Prisma.StringNullableFilter<"Candidate"> | string | null
  createdBy?: Prisma.StringFilter<"Candidate"> | string
  createdAt?: Prisma.DateTimeFilter<"Candidate"> | Date | string
}

export type CandidateCreateWithoutPositionInput = {
  id?: string
  name: string
  email: string
  status?: string
  resumeUrl?: string | null
  createdAt?: Date | string
  creator: Prisma.UserCreateNestedOneWithoutCandidatesInput
  interviews?: Prisma.InterviewCreateNestedManyWithoutCandidateInput
}

export type CandidateUncheckedCreateWithoutPositionInput = {
  id?: string
  name: string
  email: string
  status?: string
  resumeUrl?: string | null
  createdBy: string
  createdAt?: Date | string
  interviews?: Prisma.InterviewUncheckedCreateNestedManyWithoutCandidateInput
}

export type CandidateCreateOrConnectWithoutPositionInput = {
  where: Prisma.CandidateWhereUniqueInput
  create: Prisma.XOR<Prisma.CandidateCreateWithoutPositionInput, Prisma.CandidateUncheckedCreateWithoutPositionInput>
}

export type CandidateCreateManyPositionInputEnvelope = {
  data: Prisma.CandidateCreateManyPositionInput | Prisma.CandidateCreateManyPositionInput[]
  skipDuplicates?: boolean
}

export type CandidateUpsertWithWhereUniqueWithoutPositionInput = {
  where: Prisma.CandidateWhereUniqueInput
  update: Prisma.XOR<Prisma.CandidateUpdateWithoutPositionInput, Prisma.CandidateUncheckedUpdateWithoutPositionInput>
  create: Prisma.XOR<Prisma.CandidateCreateWithoutPositionInput, Prisma.CandidateUncheckedCreateWithoutPositionInput>
}

export type CandidateUpdateWithWhereUniqueWithoutPositionInput = {
  where: Prisma.CandidateWhereUniqueInput
  data: Prisma.XOR<Prisma.CandidateUpdateWithoutPositionInput, Prisma.CandidateUncheckedUpdateWithoutPositionInput>
}

export type CandidateUpdateManyWithWhereWithoutPositionInput = {
  where: Prisma.CandidateScalarWhereInput
  data: Prisma.XOR<Prisma.CandidateUpdateManyMutationInput, Prisma.CandidateUncheckedUpdateManyWithoutPositionInput>
}

export type CandidateCreateWithoutInterviewsInput = {
  id?: string
  name: string
  email: string
  status?: string
  resumeUrl?: string | null
  createdAt?: Date | string
  position: Prisma.PositionCreateNestedOneWithoutCandidatesInput
  creator: Prisma.UserCreateNestedOneWithoutCandidatesInput
}

export type CandidateUncheckedCreateWithoutInterviewsInput = {
  id?: string
  name: string
  email: string
  positionId: string
  status?: string
  resumeUrl?: string | null
  createdBy: string
  createdAt?: Date | string
}

export type CandidateCreateOrConnectWithoutInterviewsInput = {
  where: Prisma.CandidateWhereUniqueInput
  create: Prisma.XOR<Prisma.CandidateCreateWithoutInterviewsInput, Prisma.CandidateUncheckedCreateWithoutInterviewsInput>
}

export type CandidateUpsertWithoutInterviewsInput = {
  update: Prisma.XOR<Prisma.CandidateUpdateWithoutInterviewsInput, Prisma.CandidateUncheckedUpdateWithoutInterviewsInput>
  create: Prisma.XOR<Prisma.CandidateCreateWithoutInterviewsInput, Prisma.CandidateUncheckedCreateWithoutInterviewsInput>
  where?: Prisma.CandidateWhereInput
}

export type CandidateUpdateToOneWithWhereWithoutInterviewsInput = {
  where?: Prisma.CandidateWhereInput
  data: Prisma.XOR<Prisma.CandidateUpdateWithoutInterviewsInput, Prisma.CandidateUncheckedUpdateWithoutInterviewsInput>
}

export type CandidateUpdateWithoutInterviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  position?: Prisma.PositionUpdateOneRequiredWithoutCandidatesNestedInput
  creator?: Prisma.UserUpdateOneRequiredWithoutCandidatesNestedInput
}

export type CandidateUncheckedUpdateWithoutInterviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  positionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CandidateCreateManyCreatorInput = {
  id?: string
  name: string
  email: string
  positionId: string
  status?: string
  resumeUrl?: string | null
  createdAt?: Date | string
}

export type CandidateUpdateWithoutCreatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  position?: Prisma.PositionUpdateOneRequiredWithoutCandidatesNestedInput
  interviews?: Prisma.InterviewUpdateManyWithoutCandidateNestedInput
}

export type CandidateUncheckedUpdateWithoutCreatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  positionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  interviews?: Prisma.InterviewUncheckedUpdateManyWithoutCandidateNestedInput
}

export type CandidateUncheckedUpdateManyWithoutCreatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  positionId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CandidateCreateManyPositionInput = {
  id?: string
  name: string
  email: string
  status?: string
  resumeUrl?: string | null
  createdBy: string
  createdAt?: Date | string
}

export type CandidateUpdateWithoutPositionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  creator?: Prisma.UserUpdateOneRequiredWithoutCandidatesNestedInput
  interviews?: Prisma.InterviewUpdateManyWithoutCandidateNestedInput
}

export type CandidateUncheckedUpdateWithoutPositionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  interviews?: Prisma.InterviewUncheckedUpdateManyWithoutCandidateNestedInput
}

export type CandidateUncheckedUpdateManyWithoutPositionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type CandidateCountOutputType
 */

export type CandidateCountOutputType = {
  interviews: number
}

export type CandidateCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  interviews?: boolean | CandidateCountOutputTypeCountInterviewsArgs
}

/**
 * CandidateCountOutputType without action
 */
export type CandidateCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CandidateCountOutputType
   */
  select?: Prisma.CandidateCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CandidateCountOutputType without action
 */
export type CandidateCountOutputTypeCountInterviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InterviewWhereInput
}


export type CandidateSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  positionId?: boolean
  status?: boolean
  resumeUrl?: boolean
  createdBy?: boolean
  createdAt?: boolean
  position?: boolean | Prisma.PositionDefaultArgs<ExtArgs>
  creator?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  interviews?: boolean | Prisma.Candidate$interviewsArgs<ExtArgs>
  _count?: boolean | Prisma.CandidateCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["candidate"]>

export type CandidateSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  positionId?: boolean
  status?: boolean
  resumeUrl?: boolean
  createdBy?: boolean
  createdAt?: boolean
  position?: boolean | Prisma.PositionDefaultArgs<ExtArgs>
  creator?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["candidate"]>

export type CandidateSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  positionId?: boolean
  status?: boolean
  resumeUrl?: boolean
  createdBy?: boolean
  createdAt?: boolean
  position?: boolean | Prisma.PositionDefaultArgs<ExtArgs>
  creator?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["candidate"]>

export type CandidateSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  positionId?: boolean
  status?: boolean
  resumeUrl?: boolean
  createdBy?: boolean
  createdAt?: boolean
}

export type CandidateOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "positionId" | "status" | "resumeUrl" | "createdBy" | "createdAt", ExtArgs["result"]["candidate"]>
export type CandidateInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  position?: boolean | Prisma.PositionDefaultArgs<ExtArgs>
  creator?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  interviews?: boolean | Prisma.Candidate$interviewsArgs<ExtArgs>
  _count?: boolean | Prisma.CandidateCountOutputTypeDefaultArgs<ExtArgs>
}
export type CandidateIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  position?: boolean | Prisma.PositionDefaultArgs<ExtArgs>
  creator?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CandidateIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  position?: boolean | Prisma.PositionDefaultArgs<ExtArgs>
  creator?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $CandidatePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Candidate"
  objects: {
    position: Prisma.$PositionPayload<ExtArgs>
    creator: Prisma.$UserPayload<ExtArgs>
    interviews: Prisma.$InterviewPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    email: string
    positionId: string
    status: string
    resumeUrl: string | null
    createdBy: string
    createdAt: Date
  }, ExtArgs["result"]["candidate"]>
  composites: {}
}

export type CandidateGetPayload<S extends boolean | null | undefined | CandidateDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CandidatePayload, S>

export type CandidateCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CandidateFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CandidateCountAggregateInputType | true
  }

export interface CandidateDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Candidate'], meta: { name: 'Candidate' } }
  /**
   * Find zero or one Candidate that matches the filter.
   * @param {CandidateFindUniqueArgs} args - Arguments to find a Candidate
   * @example
   * // Get one Candidate
   * const candidate = await prisma.candidate.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CandidateFindUniqueArgs>(args: Prisma.SelectSubset<T, CandidateFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CandidateClient<runtime.Types.Result.GetResult<Prisma.$CandidatePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Candidate that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CandidateFindUniqueOrThrowArgs} args - Arguments to find a Candidate
   * @example
   * // Get one Candidate
   * const candidate = await prisma.candidate.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CandidateFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CandidateFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CandidateClient<runtime.Types.Result.GetResult<Prisma.$CandidatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Candidate that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CandidateFindFirstArgs} args - Arguments to find a Candidate
   * @example
   * // Get one Candidate
   * const candidate = await prisma.candidate.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CandidateFindFirstArgs>(args?: Prisma.SelectSubset<T, CandidateFindFirstArgs<ExtArgs>>): Prisma.Prisma__CandidateClient<runtime.Types.Result.GetResult<Prisma.$CandidatePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Candidate that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CandidateFindFirstOrThrowArgs} args - Arguments to find a Candidate
   * @example
   * // Get one Candidate
   * const candidate = await prisma.candidate.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CandidateFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CandidateFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CandidateClient<runtime.Types.Result.GetResult<Prisma.$CandidatePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Candidates that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CandidateFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Candidates
   * const candidates = await prisma.candidate.findMany()
   * 
   * // Get first 10 Candidates
   * const candidates = await prisma.candidate.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const candidateWithIdOnly = await prisma.candidate.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CandidateFindManyArgs>(args?: Prisma.SelectSubset<T, CandidateFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CandidatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Candidate.
   * @param {CandidateCreateArgs} args - Arguments to create a Candidate.
   * @example
   * // Create one Candidate
   * const Candidate = await prisma.candidate.create({
   *   data: {
   *     // ... data to create a Candidate
   *   }
   * })
   * 
   */
  create<T extends CandidateCreateArgs>(args: Prisma.SelectSubset<T, CandidateCreateArgs<ExtArgs>>): Prisma.Prisma__CandidateClient<runtime.Types.Result.GetResult<Prisma.$CandidatePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Candidates.
   * @param {CandidateCreateManyArgs} args - Arguments to create many Candidates.
   * @example
   * // Create many Candidates
   * const candidate = await prisma.candidate.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CandidateCreateManyArgs>(args?: Prisma.SelectSubset<T, CandidateCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Candidates and returns the data saved in the database.
   * @param {CandidateCreateManyAndReturnArgs} args - Arguments to create many Candidates.
   * @example
   * // Create many Candidates
   * const candidate = await prisma.candidate.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Candidates and only return the `id`
   * const candidateWithIdOnly = await prisma.candidate.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CandidateCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CandidateCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CandidatePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Candidate.
   * @param {CandidateDeleteArgs} args - Arguments to delete one Candidate.
   * @example
   * // Delete one Candidate
   * const Candidate = await prisma.candidate.delete({
   *   where: {
   *     // ... filter to delete one Candidate
   *   }
   * })
   * 
   */
  delete<T extends CandidateDeleteArgs>(args: Prisma.SelectSubset<T, CandidateDeleteArgs<ExtArgs>>): Prisma.Prisma__CandidateClient<runtime.Types.Result.GetResult<Prisma.$CandidatePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Candidate.
   * @param {CandidateUpdateArgs} args - Arguments to update one Candidate.
   * @example
   * // Update one Candidate
   * const candidate = await prisma.candidate.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CandidateUpdateArgs>(args: Prisma.SelectSubset<T, CandidateUpdateArgs<ExtArgs>>): Prisma.Prisma__CandidateClient<runtime.Types.Result.GetResult<Prisma.$CandidatePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Candidates.
   * @param {CandidateDeleteManyArgs} args - Arguments to filter Candidates to delete.
   * @example
   * // Delete a few Candidates
   * const { count } = await prisma.candidate.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CandidateDeleteManyArgs>(args?: Prisma.SelectSubset<T, CandidateDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Candidates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CandidateUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Candidates
   * const candidate = await prisma.candidate.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CandidateUpdateManyArgs>(args: Prisma.SelectSubset<T, CandidateUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Candidates and returns the data updated in the database.
   * @param {CandidateUpdateManyAndReturnArgs} args - Arguments to update many Candidates.
   * @example
   * // Update many Candidates
   * const candidate = await prisma.candidate.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Candidates and only return the `id`
   * const candidateWithIdOnly = await prisma.candidate.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CandidateUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CandidateUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CandidatePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Candidate.
   * @param {CandidateUpsertArgs} args - Arguments to update or create a Candidate.
   * @example
   * // Update or create a Candidate
   * const candidate = await prisma.candidate.upsert({
   *   create: {
   *     // ... data to create a Candidate
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Candidate we want to update
   *   }
   * })
   */
  upsert<T extends CandidateUpsertArgs>(args: Prisma.SelectSubset<T, CandidateUpsertArgs<ExtArgs>>): Prisma.Prisma__CandidateClient<runtime.Types.Result.GetResult<Prisma.$CandidatePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Candidates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CandidateCountArgs} args - Arguments to filter Candidates to count.
   * @example
   * // Count the number of Candidates
   * const count = await prisma.candidate.count({
   *   where: {
   *     // ... the filter for the Candidates we want to count
   *   }
   * })
  **/
  count<T extends CandidateCountArgs>(
    args?: Prisma.Subset<T, CandidateCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CandidateCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Candidate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CandidateAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CandidateAggregateArgs>(args: Prisma.Subset<T, CandidateAggregateArgs>): Prisma.PrismaPromise<GetCandidateAggregateType<T>>

  /**
   * Group by Candidate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CandidateGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CandidateGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CandidateGroupByArgs['orderBy'] }
      : { orderBy?: CandidateGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CandidateGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCandidateGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Candidate model
 */
readonly fields: CandidateFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Candidate.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CandidateClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  position<T extends Prisma.PositionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PositionDefaultArgs<ExtArgs>>): Prisma.Prisma__PositionClient<runtime.Types.Result.GetResult<Prisma.$PositionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  creator<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  interviews<T extends Prisma.Candidate$interviewsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Candidate$interviewsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InterviewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Candidate model
 */
export interface CandidateFieldRefs {
  readonly id: Prisma.FieldRef<"Candidate", 'String'>
  readonly name: Prisma.FieldRef<"Candidate", 'String'>
  readonly email: Prisma.FieldRef<"Candidate", 'String'>
  readonly positionId: Prisma.FieldRef<"Candidate", 'String'>
  readonly status: Prisma.FieldRef<"Candidate", 'String'>
  readonly resumeUrl: Prisma.FieldRef<"Candidate", 'String'>
  readonly createdBy: Prisma.FieldRef<"Candidate", 'String'>
  readonly createdAt: Prisma.FieldRef<"Candidate", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Candidate findUnique
 */
export type CandidateFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Candidate
   */
  select?: Prisma.CandidateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Candidate
   */
  omit?: Prisma.CandidateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CandidateInclude<ExtArgs> | null
  /**
   * Filter, which Candidate to fetch.
   */
  where: Prisma.CandidateWhereUniqueInput
}

/**
 * Candidate findUniqueOrThrow
 */
export type CandidateFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Candidate
   */
  select?: Prisma.CandidateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Candidate
   */
  omit?: Prisma.CandidateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CandidateInclude<ExtArgs> | null
  /**
   * Filter, which Candidate to fetch.
   */
  where: Prisma.CandidateWhereUniqueInput
}

/**
 * Candidate findFirst
 */
export type CandidateFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Candidate
   */
  select?: Prisma.CandidateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Candidate
   */
  omit?: Prisma.CandidateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CandidateInclude<ExtArgs> | null
  /**
   * Filter, which Candidate to fetch.
   */
  where?: Prisma.CandidateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Candidates to fetch.
   */
  orderBy?: Prisma.CandidateOrderByWithRelationInput | Prisma.CandidateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Candidates.
   */
  cursor?: Prisma.CandidateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Candidates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Candidates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Candidates.
   */
  distinct?: Prisma.CandidateScalarFieldEnum | Prisma.CandidateScalarFieldEnum[]
}

/**
 * Candidate findFirstOrThrow
 */
export type CandidateFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Candidate
   */
  select?: Prisma.CandidateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Candidate
   */
  omit?: Prisma.CandidateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CandidateInclude<ExtArgs> | null
  /**
   * Filter, which Candidate to fetch.
   */
  where?: Prisma.CandidateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Candidates to fetch.
   */
  orderBy?: Prisma.CandidateOrderByWithRelationInput | Prisma.CandidateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Candidates.
   */
  cursor?: Prisma.CandidateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Candidates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Candidates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Candidates.
   */
  distinct?: Prisma.CandidateScalarFieldEnum | Prisma.CandidateScalarFieldEnum[]
}

/**
 * Candidate findMany
 */
export type CandidateFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Candidate
   */
  select?: Prisma.CandidateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Candidate
   */
  omit?: Prisma.CandidateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CandidateInclude<ExtArgs> | null
  /**
   * Filter, which Candidates to fetch.
   */
  where?: Prisma.CandidateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Candidates to fetch.
   */
  orderBy?: Prisma.CandidateOrderByWithRelationInput | Prisma.CandidateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Candidates.
   */
  cursor?: Prisma.CandidateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Candidates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Candidates.
   */
  skip?: number
  distinct?: Prisma.CandidateScalarFieldEnum | Prisma.CandidateScalarFieldEnum[]
}

/**
 * Candidate create
 */
export type CandidateCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Candidate
   */
  select?: Prisma.CandidateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Candidate
   */
  omit?: Prisma.CandidateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CandidateInclude<ExtArgs> | null
  /**
   * The data needed to create a Candidate.
   */
  data: Prisma.XOR<Prisma.CandidateCreateInput, Prisma.CandidateUncheckedCreateInput>
}

/**
 * Candidate createMany
 */
export type CandidateCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Candidates.
   */
  data: Prisma.CandidateCreateManyInput | Prisma.CandidateCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Candidate createManyAndReturn
 */
export type CandidateCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Candidate
   */
  select?: Prisma.CandidateSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Candidate
   */
  omit?: Prisma.CandidateOmit<ExtArgs> | null
  /**
   * The data used to create many Candidates.
   */
  data: Prisma.CandidateCreateManyInput | Prisma.CandidateCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CandidateIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Candidate update
 */
export type CandidateUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Candidate
   */
  select?: Prisma.CandidateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Candidate
   */
  omit?: Prisma.CandidateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CandidateInclude<ExtArgs> | null
  /**
   * The data needed to update a Candidate.
   */
  data: Prisma.XOR<Prisma.CandidateUpdateInput, Prisma.CandidateUncheckedUpdateInput>
  /**
   * Choose, which Candidate to update.
   */
  where: Prisma.CandidateWhereUniqueInput
}

/**
 * Candidate updateMany
 */
export type CandidateUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Candidates.
   */
  data: Prisma.XOR<Prisma.CandidateUpdateManyMutationInput, Prisma.CandidateUncheckedUpdateManyInput>
  /**
   * Filter which Candidates to update
   */
  where?: Prisma.CandidateWhereInput
  /**
   * Limit how many Candidates to update.
   */
  limit?: number
}

/**
 * Candidate updateManyAndReturn
 */
export type CandidateUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Candidate
   */
  select?: Prisma.CandidateSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Candidate
   */
  omit?: Prisma.CandidateOmit<ExtArgs> | null
  /**
   * The data used to update Candidates.
   */
  data: Prisma.XOR<Prisma.CandidateUpdateManyMutationInput, Prisma.CandidateUncheckedUpdateManyInput>
  /**
   * Filter which Candidates to update
   */
  where?: Prisma.CandidateWhereInput
  /**
   * Limit how many Candidates to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CandidateIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Candidate upsert
 */
export type CandidateUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Candidate
   */
  select?: Prisma.CandidateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Candidate
   */
  omit?: Prisma.CandidateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CandidateInclude<ExtArgs> | null
  /**
   * The filter to search for the Candidate to update in case it exists.
   */
  where: Prisma.CandidateWhereUniqueInput
  /**
   * In case the Candidate found by the `where` argument doesn't exist, create a new Candidate with this data.
   */
  create: Prisma.XOR<Prisma.CandidateCreateInput, Prisma.CandidateUncheckedCreateInput>
  /**
   * In case the Candidate was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CandidateUpdateInput, Prisma.CandidateUncheckedUpdateInput>
}

/**
 * Candidate delete
 */
export type CandidateDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Candidate
   */
  select?: Prisma.CandidateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Candidate
   */
  omit?: Prisma.CandidateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CandidateInclude<ExtArgs> | null
  /**
   * Filter which Candidate to delete.
   */
  where: Prisma.CandidateWhereUniqueInput
}

/**
 * Candidate deleteMany
 */
export type CandidateDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Candidates to delete
   */
  where?: Prisma.CandidateWhereInput
  /**
   * Limit how many Candidates to delete.
   */
  limit?: number
}

/**
 * Candidate.interviews
 */
export type Candidate$interviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interview
   */
  select?: Prisma.InterviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interview
   */
  omit?: Prisma.InterviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InterviewInclude<ExtArgs> | null
  where?: Prisma.InterviewWhereInput
  orderBy?: Prisma.InterviewOrderByWithRelationInput | Prisma.InterviewOrderByWithRelationInput[]
  cursor?: Prisma.InterviewWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InterviewScalarFieldEnum | Prisma.InterviewScalarFieldEnum[]
}

/**
 * Candidate without action
 */
export type CandidateDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Candidate
   */
  select?: Prisma.CandidateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Candidate
   */
  omit?: Prisma.CandidateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CandidateInclude<ExtArgs> | null
}
